Fix warning found by clang: private unused members in a class
qremoteserviceregister_dbus_p.h:151:22: error: private field 'connection' is not used [-Werror,-Wunused-private-field]

Change-Id: I445b478857e0807b468e5ba1daa92fa1c8c7d9da
Reviewed-by: Alex Blasche <alexander.blasche@digia.com>