Fix invalid use of lambda expressions in noexcept expression.
Using a QStringLiteral within a Q_GLOBAL_STATIC_WITH_ARGS macro
expansion results in the following error when lambda experssions are
available, such as when building with GCC 4.7:

qdisplayinfo_linux.cpp: In function ‘{anonymous}::Q_QGS_BACKLIGHT_SYSFS_PATH::Type* {anonymous}::Q_QGS_BACKLIGHT_SYSFS_PATH::innerFunction()’:
qdisplayinfo_linux.cpp:50:1: error: lambda-expression in unevaluated context
qdisplayinfo_linux.cpp: In lambda function:
qdisplayinfo_linux.cpp:50:1: error: types may not be defined in ‘noexcept’ expressions
qdisplayinfo_linux.cpp:50:1: error: ‘Size’ was not declared in this scope
qdisplayinfo_linux.cpp:50:1: error: template argument 1 is invalid
qdisplayinfo_linux.cpp:50:1: error: invalid type in declaration before ‘=’ token
qdisplayinfo_linux.cpp:50:1: error: scalar object ‘qstring_literal’ requires one element in initializer

The noexcept expressions is defined at qglobalstatic.h:76

Fixed by using QLatin1String instead, which can be used in this
context.

Change-Id: Ia7f8219499ff348a4dc3f7dafb4641a96a982eb0
Reviewed-by: Laszlo Papp <lpapp@kde.org>
Reviewed-by: Lorn Potter <lorn.potter@jollamobile.com>