Fix interesting warning found in publish-and-subscribe
jsondblayer.cpp:171:24: error: a temporary bound to ‘JsonDbSyncCall::mQuery’ only persists until the constructor exits [-Werror=extra]

This is probably a bug in the code. I have no clue why it needs to
initialise to "". That's REALLY weird.

Change-Id: I81f833235924ec51380a128ba73a59f9cbbbaa4f
Reviewed-by: Aaron McCarthy <mccarthy.aaron@gmail.com>